"""
Deterministic Explainable Risk Scorer.
Computes a weighted 0-100 risk score and tier classification with an explicit breakdown of contributing factors.
The score is 100% deterministic and rule-based (never generated by an LLM).
"""

from typing import Any, Dict, List, Optional
from fir_intelligence.phase3_analytics.models import EntityMetrics
from .models import ContributingFactor, RiskScore, ScoringConfig


class RiskScorer:
    """
    Computes explainable risk scores for entities based on Phase 3 graph metrics and pattern matches.
    """

    def __init__(self, config: Optional[ScoringConfig] = None):
        self.config = config or ScoringConfig()

    def score_entity(
        self,
        metrics: EntityMetrics,
        display_value: str = "",
        entity_type: str = "Unknown",
    ) -> RiskScore:
        """
        Calculates normalized 0-100 risk score and builds contributing factor breakdown.
        """
        factors: List[ContributingFactor] = []

        # 1. Cross-FIR Appearance Factor (up to cross_fir_weight points)
        xfir_count = metrics.cross_fir_count
        if xfir_count >= 2:
            xfir_pts = min(self.config.cross_fir_weight, (xfir_count - 1) * 12.5)
            factors.append(
                ContributingFactor(
                    factor_name="cross_fir_appearances",
                    raw_value=xfir_count,
                    points_contributed=round(xfir_pts, 1),
                    description=f"Appears across {xfir_count} separate FIRs",
                )
            )

        # 2. Shared Identifier Pattern Factor (up to repeated_identifier_points)
        if "repeated_identifier" in metrics.pattern_flags:
            rep_pts = self.config.repeated_identifier_points
            factors.append(
                ContributingFactor(
                    factor_name="shared_identifier_pattern",
                    raw_value=True,
                    points_contributed=round(rep_pts, 1),
                    description="Shared identifier linked to multiple distinct person entities",
                )
            )

        # 3. PageRank Centrality Factor (up to pagerank_max_points)
        pr_val = metrics.centrality.pagerank
        if pr_val > 0:
            pr_pts = min(self.config.pagerank_max_points, pr_val * 200.0)
            if pr_pts >= 1.0:
                factors.append(
                    ContributingFactor(
                        factor_name="pagerank_influence",
                        raw_value=pr_val,
                        points_contributed=round(pr_pts, 1),
                        description=f"High network PageRank influence score ({pr_val:.4f})",
                    )
                )

        # 4. Betweenness Centrality Factor (up to betweenness_max_points)
        bw_val = metrics.centrality.betweenness_centrality
        if bw_val > 0:
            bw_pts = min(self.config.betweenness_max_points, bw_val * 100.0)
            if bw_pts >= 1.0:
                factors.append(
                    ContributingFactor(
                        factor_name="betweenness_brokerage",
                        raw_value=bw_val,
                        points_contributed=round(bw_pts, 1),
                        description=f"Acts as a key network broker between clusters (Betweenness {bw_val:.4f})",
                    )
                )

        # 5. Dense Cluster Membership Factor (up to dense_cluster_points)
        if "dense_cluster" in metrics.pattern_flags:
            cluster_pts = self.config.dense_cluster_points
            factors.append(
                ContributingFactor(
                    factor_name="dense_cluster_membership",
                    raw_value=metrics.community_id,
                    points_contributed=round(cluster_pts, 1),
                    description=f"Located in a high-density network cluster (Community {metrics.community_id})",
                )
            )

        # 6. Star Pattern Controller Factor (up to unusual_structure_points)
        if "unusual_structure" in metrics.pattern_flags:
            star_pts = self.config.unusual_structure_points
            factors.append(
                ContributingFactor(
                    factor_name="star_pattern_controller",
                    raw_value=True,
                    points_contributed=round(star_pts, 1),
                    description="Central controller hub in an unusual star-topology network",
                )
            )

        # Total score computation and clamping
        raw_total = sum(f.points_contributed for f in factors)
        final_score = round(max(0.0, min(100.0, raw_total)), 1)

        # Risk Tier Classification
        if final_score >= self.config.high_tier_cutoff:
            tier = "HIGH"
        elif final_score >= self.config.low_tier_cutoff:
            tier = "MEDIUM"
        else:
            tier = "LOW"

        return RiskScore(
            entity_id=metrics.entity_id,
            display_value=display_value or metrics.entity_id,
            entity_type=entity_type,
            score=final_score,
            tier=tier,
            contributing_factors=factors,
        )
